// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCttZiZ0QB2Xi5slZ5V5ZbI-DFUq5jDymk',
    appId: '1:76487740850:web:333998d431b64ed3f4a8ab',
    messagingSenderId: '76487740850',
    projectId: 'employee-83073',
    authDomain: 'employee-83073.firebaseapp.com',
    storageBucket: 'employee-83073.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksvspBj8H4BEeT0l9OtYrFKGAYvm8SWE',
    appId: '1:76487740850:android:3e648c4bcfdb8b26f4a8ab',
    messagingSenderId: '76487740850',
    projectId: 'employee-83073',
    storageBucket: 'employee-83073.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXcRWIHuj-Jtr0y8SPi_MwwAld-ZvdVi0',
    appId: '1:76487740850:ios:09ee4296c8501501f4a8ab',
    messagingSenderId: '76487740850',
    projectId: 'employee-83073',
    storageBucket: 'employee-83073.firebasestorage.app',
    iosClientId: '76487740850-vlf87apukqvg5arpdmqsq67kd82q8502.apps.googleusercontent.com',
    iosBundleId: 'com.github.roadmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXcRWIHuj-Jtr0y8SPi_MwwAld-ZvdVi0',
    appId: '1:76487740850:ios:09ee4296c8501501f4a8ab',
    messagingSenderId: '76487740850',
    projectId: 'employee-83073',
    storageBucket: 'employee-83073.firebasestorage.app',
    iosClientId: '76487740850-vlf87apukqvg5arpdmqsq67kd82q8502.apps.googleusercontent.com',
    iosBundleId: 'com.github.roadmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCttZiZ0QB2Xi5slZ5V5ZbI-DFUq5jDymk',
    appId: '1:76487740850:web:171bd03e63f7c906f4a8ab',
    messagingSenderId: '76487740850',
    projectId: 'employee-83073',
    authDomain: 'employee-83073.firebaseapp.com',
    storageBucket: 'employee-83073.firebasestorage.app',
  );
}
